name: Publish
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node (with npm auth)
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
